### ISSUE TITLE
DtdProcessing.Prohibit in extensions?

### ISSUE THREAD

**Issue by huan086** [ITfoxtec/ITfoxtec.SAML2#4]
Should DtdProcessing.Prohibit be set in extensions as well to prevent XXE?

Specifically XDocumentExtensions and XElementExtensions

**Comment by Revsgaard** [comment]
The DtdProcessing = DtdProcessing.Prohibit is actually default but still I think it is a good idea to add it for explicitly.

**Comment by huan086** [comment]
Didn't realize XElement.CreateReader() has DtdProcessing.Prohibit as default, unlike XmlReader which has DtdProcessing.Parse as default.

Thanks for the quick reply =)
