### ISSUE TITLE
Where is the source code for 1.2.4?

### ISSUE THREAD

**Issue by StilgarISCA** [ITfoxtec/ITfoxtec.SAML2#5]
The [currently published NuGet package is 1.2.4](https://www.nuget.org/packages/ITfoxtec.Saml2/), but your releases aren't indicated or tagged so I'm not sure what code is included in the NuGet package.

When you shipped 1.2.1, the version was changed in this AssemblyInfo commit 5ca75df. Similarly, 1.2.2 shipped with 87adeb3 named "New Version." Version 1.2.3 is tucked away here c40e4b4.

I can't find any commit at all where the version changed to 1.2.4, and master still lists it as 1.2.3. Maybe a file was missed during a git add/commit? I dunno. What assurance do I have that other changes aren't missing from the repo?

This also leads me to question where your NuGet packages are being built from. If they're being built from Master in the repository we'd still be at 1.2.3.

Please correct the issue. I'd also ask that you start tagging your releases in GitHub so it's more obvious and trackable which code is associated with the NuGet package.

**Comment by Revsgaard** [comment]
Thank you for the post and bringing the problem to my attention. I had forgotten to commit/sync the changes to GitHub.

I have tagged the release and will do that from now on.
